### PR TITLE
Removed ip address

### PR DESCRIPTION
**Pull request by coderaiser**
Removed ip address to connect from any.

### CODE REVIEW

**Comment by Gottox** [comment]
e86fb5b5dc1ba064f405a38398dd04a2fd45aafa is okay. But I won't include the other patches as it's totally unsafe to listen on the network with webterm by default if you're not 100% sure about what you're doing.

**Comment by coderaiser** [comment]
If `webterm` woud be used as `express` middleware people coud connect `http-auth` or any other auth way for authentication. Shoud web terminal really handle such things?

**Comment by Gottox** [comment]
It's a demo project for terminal.js and child_pty. It's purpose is to show how terminal.js can be set up in a web application.

Making an express middleware from it is an hard task, as express is not designed to provide bidirectional IO. If you wan't to implement a module, feel free to set it up :)

**Comment by coderaiser** [comment]
Actually I have a [similar module](https://github.com/cloudcmd/console) for same purpose and I think `terminal.js` could be used as middleware as well.

**Pull request closed without merging**
